from tkinter import *
root = Tk()
root.config(background = "yellow")

def click(event):
    global scvalue
    text = event.widget.cget("text")
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            try:
                value = eval(screen.get())
            except Exception as e:
                a = "Error"
                scvalue.set(a)
                screen.update()

        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root.geometry("644x550")
root.wm_iconbitmap("icon.ico")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvariable = scvalue,font = "lucida 40 bold",relief = SUNKEN)
screen.pack(side = TOP, fill = X,padx = 10,pady = 10)
f = Frame(root, width=100,bg = "yellow")
f.pack(fill=Y, side=LEFT)
f_1 = Frame(root,width = 100,bg = "yellow")
f_1.pack(side = RIGHT)
f1 = Frame(root,bg = "yellow")
f1.pack(side = TOP,fill = X)
b9 = Button(f1,bg = "grey",text = "9",font = "lucida 30 bold",padx = 15,pady = 15)
b9.pack(side = LEFT)
b9.bind('<Button-1>',click)
b8 = Button(f1,bg = "grey",text = "8",font = "lucida 30 bold",padx = 15,pady = 15)
b8.pack(side = LEFT,padx = 18)
b8.bind('<Button-1>',click)
b7 = Button(f1,bg = "grey",text = "7",font = "lucida 30 bold",padx = 15,pady = 15)
b7.pack(side = LEFT)
b7.bind('<Button-1>',click)
bclear = Button(f1,bg = "grey",text = "C",font = "lucida 30 bold",padx = 15,pady = 15)
bclear.pack(side = LEFT,padx = 17)
bclear.bind('<Button-1>',click)
f2 = Frame(root,bg = "yellow")
f2.pack(side = TOP,fill = X)
b6 = Button(f2,bg = "grey",text = "6",font = "lucida 30 bold",padx = 15,pady = 15)
b6.pack(side = LEFT)
b6.bind('<Button-1>',click)
b5 = Button(f2,bg = "grey",text = "5",font = "lucida 30 bold",padx = 15,pady = 15)
b5.pack(side = LEFT,padx = 18)
b5.bind('<Button-1>',click)
b4 = Button(f2,bg = "grey",text = "4",font = "lucida 30 bold",padx = 15,pady = 15)
b4.pack(side = LEFT)
b4.bind('<Button-1>',click)
bequal = Button(f2,bg = "grey",text = "=",font = "lucida 30 bold",padx = 18,pady = 15)
bequal.pack(side = LEFT,padx = 17)
bequal.bind('<Button-1>',click)
f3 = Frame(root,bg = "yellow")
f3.pack(side = TOP,fill = X)
b3 = Button(f3,bg = "grey",text = "3",font = "lucida 30 bold",padx = 15,pady = 15)
b3.pack(side = LEFT)
b3.bind('<Button-1>',click)
b2 = Button(f3,bg = "grey",text = "2",font = "lucida 30 bold",padx = 15,pady = 15)
b2.pack(side = LEFT,padx = 18)
b2.bind('<Button-1>',click)
b1 = Button(f3,bg = "grey",text = "1",font = "lucida 30 bold",padx = 15,pady = 15)
b1.pack(side = LEFT)
b1.bind('<Button-1>',click)
bmul = Button(f3,bg = "grey",text = "*",font = "lucida 30 bold",padx = 21,pady = 15)
bmul.pack(side = LEFT,padx = 17)
bmul.bind('<Button-1>',click)
f4 = Frame(root,bg = "yellow")
f4.pack(side = TOP,fill = X)
b0 = Button(f4,bg = "grey",text = "0",font = "lucida 30 bold",padx = 15,pady = 15)
b0.pack(side = LEFT)
b0.bind('<Button-1>',click)
bmin = Button(f4,bg = "grey",text = "-",font = "lucida 30 bold",padx = 19,pady = 15)
bmin.pack(side = LEFT,padx = 18)
bmin.bind('<Button-1>',click)
bplus = Button(f4,bg = "grey",text = "+",font = "lucida 30 bold",padx = 15,pady = 15)
bplus.pack(side = LEFT,padx = 1)
bplus.bind('<Button-1>',click)
bdiv = Button(f4,bg = "grey",text = "/",font = "lucida 30 bold",padx = 24,pady = 15)
bdiv.pack(side = LEFT,padx = 14)
bdiv.bind('<Button-1>',click)
root.mainloop()